name: System Tests
description: Run Newman API tests against deployed API.

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  performance-tests:
    name: Performance Tests (PT)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
     
      - name: Install k6
        run: sudo snap install k6

      - name: Run Performance Tests
        working-directory: src/tests/ReferenceDataApi.PerformanceTests
        run: k6 run tests/performance/performance-tests.js

  smoke-tests:
    name: Smoke Tests (ST)
    needs: performance-tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman collection
        working-directory: src/tests/ReferenceDataApi.SystemTests
        run: newman run smoke-tests.json --environment environment.json

  functional-tests:
    name: Functional Tests (FT)
    needs: smoke-tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman collection
        working-directory: src/tests/ReferenceDataApi.SystemTests
        run: newman run functional-tests.json --environment environment.json

  authentication-tests:
    name: Authentication Tests (AT)
    needs: functional-tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman collection
        working-directory: src/tests/ReferenceDataApi.SystemTests
        run: newman run authentication-tests.json --environment environment.json

  validation-tests:
    name: Validation Tests (VT)
    needs: authentication-tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman collection
        working-directory: src/tests/ReferenceDataApi.SystemTests
        run: newman run validation-tests.json --environment environment.json