name: System Tests
description: Run Postman collection API tests against deployed API.

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    name: Functional Tests (FT)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman collection
        working-directory: src/tests/ReferenceDataApi.SystemTests
        run: |
          newman run functional-tests.json --environment environment.json